#!/bin/sh

# carregar variáveis/funções
. ./function.sh
inst_launch_workaround

PATH=./:$PATH
LOG_DIR="./log"

print_start() {
	#    more << EOF
	echo "rAthena está iniciando..."
	echo "            (c) 2021 Projeto rAthena"
	echo ""
	echo ""
	echo "verificando..."
	#EOF
}

get_status(){
	PIDFILE=.$1.pid
	if [ -e ${PIDFILE} ]; then
		PSRUN=$(pgrep -F ${PIDFILE})
	fi
	#return ${PSRUN} #parece causar problemas em alguns sistemas
}

# verifica se já está iniciado, inicia e registra no log
start_serv(){ 
	get_status $1
	if [ $2 ]; then # logging ativado?
		LOGFILE="$LOG_DIR/$1.launch.log"
		LOGRUN="$LOG_DIR/$1.log"
		FIFO="$1_fifo"
		echo "stat_serv, logging ativado"
		echo "Meu arquivo de log=${LOGFILE}"
		if [ -z ${PSRUN} ]; then
			if [ -e ./${FIFO} ]; then rm "$FIFO"; fi
			mkfifo "$FIFO"; tee "$LOGRUN" < "$FIFO" & "./$1" > "$FIFO" 2>&1 & PID=$!
			#"./$1" > >(tee "$LOGRUN") 2>&1 & PID=$! #somente bash
			echo "$PID" > .$1.pid
			echo "Servidor '$1' iniciado em $(date +"%m-%d-%H:%M-%S")" | tee ${LOGFILE}
		else
			echo "Não foi possível iniciar '$1', pois ele já está em execução p${PSRUN}" | tee ${LOGFILE}
		fi
	else
		if [ -z ${PSRUN} ]; then
			./$1&
			echo "$!" > .$1.pid
			echo "Servidor '$1' iniciado em $(date +"%m-%d-%H:%M-%S")"
		else
			echo "Não foi possível iniciar '$1', pois ele já está em execução p${PSRUN}"
		fi
	fi
}

watch_serv(){
	ulimit -Sc unlimited

	# agora verificando status e entrando em loop
	count=0;
	while true; do
		for i in ${L_SRV} ${C_SRV} ${M_SRV} ${W_SRV}
		do
			LOGFILE="$LOG_DIR/$i.launch.log"
			LOGRUN="$LOG_DIR/$i.log"
			FIFO=$i"_fifo"

			get_status ${i}
			#echo "PID de $i é ${PSRUN}"
			if [ -z ${PSRUN} ]; then
				count=$((count+1))
				#echo "fifo=$FIFO"
				echo "servidor '$i' está desligado"
				echo "servidor '$i' está desligado" >> ${LOGFILE}
				echo "reiniciando servidor em $(date +"%m-%d-%H:%M-%S")"
				echo "reiniciando servidor em $(date +"%m-%d-%H:%M-%S")" >> ${LOGFILE}
				if [ -e $FIFO ]; then rm $FIFO; fi
				mkfifo "$FIFO"; tee "$LOGRUN" < "$FIFO" & "./$i" > "$FIFO" 2>&1 & PID=$!
				echo "$PID" > .$i.pid
				if [ $2 ] && [ $2 -lt $count ]; then break; fi
			fi
		done
		sleep $1
	done
}

restart(){
	$0 stop
	if [ $1 ]; then sleep $1; fi
	for i in ${L_SRV} ${C_SRV} ${M_SRV} ${W_SRV}
	do
		FIFO="$1_fifo"
		while true; do
			get_status ${i}
			if [ ${PSRUN} ]; then
				echo "'${i}' ainda está em execução p${PSRUN}, aguardando o processo finalizar"
				sleep 2
			else 
				if [ -e ./${FIFO} ]; then rm "$FIFO"; fi
				break
			fi
		done
	done
	$0 start
}

case $1 in
	'start')
		print_start
		check_files
		echo "Verificação concluída."
		echo "Parece um rAthena bonito e saudável!"
		if [ "$2" = "--enlog" ]; then
		 ENLOG=1
		 if [ ! -d "$LOG_DIR" ]; then mkdir -p $LOG_DIR; fi
		 echo "Logging ativado em $LOG_DIR"
		else
		 echo "Logging desativado"
		fi
		for i in ${L_SRV} ${C_SRV} ${M_SRV} ${W_SRV}
		do
			start_serv $i $ENLOG
		done
		echo "rAthena foi iniciado."
	;;
	'watch')
		if [ ! -d "$LOG_DIR" ]; then mkdir -p $LOG_DIR; fi
		if [ -z $2 ]; then Restart_count=10; else Restart_count=$2; fi
		if [ -z $3 ]; then Restart_sleep=3; else Restart_sleep=$3; fi
		echo "Monitorando rAthena com restart_count = $Restart_count, restart_sleep = $Restart_sleep"
		for i in ${L_SRV} ${C_SRV} ${M_SRV} ${W_SRV}
		do
			start_serv $i 1
		done
		watch_serv $Restart_count $Restart_sleep
		echo "rAthena agora está sendo monitorado."
	;;
	'stop')
		for i in ${W_SRV} ${M_SRV} ${C_SRV} ${L_SRV}
		do
			PIDFILE=.${i}.pid
			if [ -e ./${PIDFILE} ]; then
				kill $(cat ${PIDFILE})
				
				while true; do
					get_status ${i}
					if [ ${PSRUN} ]; then
						echo "'${i}' ainda está em execução p${PSRUN}, aguardando o processo finalizar"
						sleep 2
					else
						break
					fi
				done
				
				rm ${PIDFILE}
			fi
		done
	;;
	'restart')
		 restart "$@"
	;;
	'status')
		for i in ${L_SRV} ${C_SRV} ${M_SRV} ${W_SRV}
		do
			get_status ${i}
			if [ ${PSRUN} ]; then
				echo "'${i}' está em execução p${PSRUN}"
			else
				echo "'${i}' parece estar desligado"
			fi
		done
	;;
	'val_runonce')
		for i in ${L_SRV} ${C_SRV} ${M_SRV} ${W_SRV}
		do
			valgrind --leak-check=full --show-leak-kinds=all ./$i --run-once > "log/$i.runonce.leak"
		done
	;;
	'valchk')
		for i in ${L_SRV} ${C_SRV} ${M_SRV} ${W_SRV}
		do
			valgrind --leak-check=full --show-leak-kinds=all ./$i > "log/$i.runonce.leak"
		done
	;;
	'help')
		case $2 in
			'start')
				echo "sintaxe: 'start {--enlog}'"
				echo "Esta opção iniciará os servidores"
				echo "--enlog gravará toda a saída do terminal em log/\$nomedoservidor.log"
			;;
			'stop')
				echo "Esta opção encerrará os servidores"
			;;
			'restart')
				echo "sintaxe: 'restart {<atraso>}'"
				echo "Esta opção aguardará o atraso informado e tentará reiniciar os servidores"
				echo "Nota: Mesmo após o atraso, aguardará o término do PID antes de reiniciar"
			;;
			'status')
				echo "sintaxe: 'status'"
				echo "Esta opção informa se os servidores estão em execução ou não"
				echo "Nota: Baseia-se em PID e requer que os servidores tenham sido iniciados por este script"
				echo "Caso contrário, utilize algo como 'ps ax | grep server' para verificar o status"
			;;
			'watch')
				echo "sintaxe: 'watch {<intervalo_restart> <quantidade_restart>}'"
				echo "A opção watch permite reiniciar automaticamente os servidores quando algum for encerrado"
				echo "<intervalo_restart> atraso em segundos antes de revalidar (padrão 10)"
				echo "<quantidade_restart> quantas vezes reiniciar (padrão 3), (-1 = indefinido)"
			;;
			'val_runonce')
				echo "sintaxe: 'val_runonce'"
				echo "Esta opção executa o valgrind com run-once para verificar os servidores"
			;;
			'valchk')
				echo "sintaxe: 'valchk'"
				echo "Esta opção executa o valgrind com os servidores em execução"
			;;
			*)
				echo "Por favor, informe um comando válido { start | stop | restart | status | watch }"
				read -p "Digite um comando válido: " readEnterKey
				$0 "help" $readEnterKey
			;;
		esac
	;;
	*)
		echo "Uso: athena-start { start | stop | restart | status | watch | help | val_runonce | valchk }"
		read -p "Digite uma opção válida: " readEnterKey
		$0 $readEnterKey
	;;
esac
