name: Bug Report
description: Criar um Relatório detalhando comportamento quebrado ou inesperado
labels: ["type:bug"]
body:
  - type: input
    id: hash
    attributes:
      label: Hash do rAthena
      description: |
        Por favor, especifique o [hash do GitHub](https://help.github.com/articles/autolinked-references-and-urls/#commit-shas) do rAthena no qual você encontrou este problema.
        Uma forma de obter o hash é digitando `git rev-parse --short HEAD` no seu console.
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Data do Cliente
      description: Especifique a data do cliente que você está usando quando este problema ocorreu.
      placeholder: YYYY-MM-DD
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Modo do Servidor
      description: Especifique o modo do servidor que você está usando quando este problema ocorreu.
      multiple: true
      options:
        - Pré-Renewal
        - Renewal
    validations:
      required: true

  - type: textarea
    id: result
    attributes:
      label: Resultado
      description: Descreva o problema que você experienciou em detalhes.
      placeholder: |
        1. Neste ambiente...
        2. Com esta configuração...
        3. Disparar o evento '...'
        4. Ver erro...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Saída de Log Relevante
      description: Copie e cole qualquer saída de log relevante. Isso será automaticamente formatado como código, então não há necessidade de crases.
      render: Shell
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Resultado Esperado
      description: Descreva em detalhes o que você esperava que acontecesse.
    validations:
      required: true

  - type: textarea
    id: howto
    attributes:
      label: Como Reproduzir
      description: Caso ainda não tenha explicado na descrição do resultado, forneça um guia curto de como podemos reproduzir o problema.
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: Informações Oficiais
      description: Se possível, forneça informações de servidores oficiais (kRO ou outras fontes) que provem que o resultado está errado. Leve em conta que iRO (especialmente iRO Wiki) nem sempre é igual ao kRO.
    validations:
      required: true

  - type: textarea
    id: modifications
    attributes:
      label: Modificações que podem afetar os resultados
      description: |
        Se você estiver usando quaisquer modificações, especialmente em /src/, você deve listá-las aqui.
        Mesmo alterações pequenas podem causar problemas. Precisamos saber o que você personalizou.
        Isso pode incluir configurações modificadas, valores alterados no banco de dados, ou até modificações externas no source.
