name: Solicitação de Funcionalidade
description: Sugira uma ideia para este projeto
labels: ["type:enhancement"]
body:
  - type: dropdown
    id: missing
    attributes:
      label: Sua solicitação está relacionada a uma funcionalidade oficial ausente?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Descreva a solução desejada
      description: Forneça uma descrição clara e concisa do que você gostaria que acontecesse.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Descreva as alternativas que você considerou
      description: Conte-nos sobre outras soluções que você tentou ou pesquisou.
  - type: textarea
    id: context
    attributes:
      label: Contexto adicional
      description: |
        Há algo mais que você possa adicionar sobre a proposta?
        Talvez você queira adicionar links para issues relacionadas aqui, caso ainda não o tenha feito.
