name: Solicitação de Recurso
description: Sugerir uma ideia para este projeto
labels: ["type:enhancement"]
body:
  - type: dropdown
    id: missing
    attributes:
      label: Sua solicitação está relacionada a um recurso oficial ausente?
      options:
        - "Sim"
        - "Não"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Descreva a solução desejada
      description: Forneça uma descrição clara e concisa do que você quer que aconteça.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Descreva alternativas que você considerou
      description: Informe-nos sobre outras soluções que você tentou ou pesquisou.
  - type: textarea
    id: context
    attributes:
      label: Contexto adicional
      description: |
        Há mais alguma coisa que você possa acrescentar sobre a proposta?
        Você pode querer incluir links para issues relacionadas aqui, caso ainda não tenha feito isso.
