//--------------------------------------------------------------
// Arquivo de Configuração de Batalha do rAthena
// Originalmente traduzido por Peter Kieser <pfak@telus.net>
// Tornado em inglês mais simples por Ancyker
// Dividido em vários arquivos por Skotlex.
//--------------------------------------------------------------

//Configurações gerais relacionadas a batalha.
import: conf/battle/battle.conf

//Configurações do Campo de Batalha (Battleground)
import: conf/battle/battleground.conf

//Configurações específicas do cliente.
import: conf/battle/client.conf

//Configurações gerais relacionadas a drops.
import: conf/battle/drops.conf

//Taxas de experiência, penalidades de EXP, atributos e níveis máximos.
import: conf/battle/exp.conf

//Controle de recursos (ligado/desligado)
import: conf/battle/feature.conf

//Níveis de GM, atcommands e configurações relacionadas a hacks.
import: conf/battle/gm.conf

//Configurações de Guilda e Guerra do Emperium (WoE)
import: conf/battle/guild.conf

//Configurações relacionadas a Homúnculos
import: conf/battle/homunc.conf

//Configurações de Instâncias
import: conf/battle/instance.conf

//Opções específicas de itens/cartas e relacionadas a criação (crafting).
import: conf/battle/items.conf

//Configurações relacionadas a monstros (Mobs)
import: conf/battle/monster.conf

// Qualquer outra coisa que não se encaixe em outro lugar.
// Inclui duelo, dia/noite, mute/manners, configurações de log.
import: conf/battle/misc.conf

//Configurações relacionadas a grupo (Party)
import: conf/battle/party.conf

//Configurações relacionadas a Pets
import: conf/battle/pet.conf

//Configurações específicas do jogador
import: conf/battle/player.conf

//Configurações relacionadas a habilidades (Skills)
import: conf/battle/skill.conf

//Configurações relacionadas a alterações de status
import: conf/battle/status.conf

//Sua configuração personalizada vai aqui.
import: conf/import/battle_conf.txt
