//--------------------------------------------------------
// Arquivo de Configuração de Scripts do rAthena
//--------------------------------------------------------


warn_func_mismatch_paramnum: yes

check_cmdcount: 655360

check_gotocount: 2048

// Valor padrão do argumento 'min' do comando de script 'input'.
// Quando o argumento 'min' não é fornecido, este valor é usado.
// Padrão: 0.
//input_min_value: 0

// Valor padrão do argumento 'max' do comando de script 'input'.
// Quando o argumento 'max' não é fornecido, este valor é usado.
// Padrão: INT_MAX.
//input_max_value: 2147483647
input_max_value: 10000000

// Especifica se os argumentos de cada função interna serão verificados
// quanto ao tipo correto. Quando uma função recebe um argumento diferente
// do que ela espera, um aviso é exibido antes da função ser executada mesmo assim.
// Padrão: yes
warn_func_mismatch_argtypes: yes

import: conf/import/script_conf.txt
