//--------------------------------------------------------------
// Arquivo de Configuração de Batalha do rAthena
// Originalmente traduzido por Peter Kieser <pfak@telus.net>
// Adaptado para um inglês mais simples por Ancyker
//--------------------------------------------------------------
// Nota 1: O valor é um interruptor de configuração (ligado/desligado, sim/não ou 1/0)
// Nota 2: O valor está em porcentagem (100 significa 100%)
// Nota 3: O valor é um campo de bits. Se nenhuma descrição for fornecida,
//         assuma os tipos de unidades (1: Pc, 2: Mob, 4: Pet, 8: Homun, 16: Mercenário, 128: NPC, 512: Elemental)
//--------------------------------------------------------------

// Ajustes de dano corpo a corpo (sem habilidades) para mapas de Campos de Batalha (Nota 2)
bg_short_attack_damage_rate: 80

// Ajustes de dano à distância (sem habilidades) para mapas de Campos de Batalha (Nota 2)
bg_long_attack_damage_rate: 80

// Ajustes de dano de habilidades de arma para mapas de Campos de Batalha (Nota 2)
bg_weapon_attack_damage_rate: 60

// Ajustes de dano de habilidades mágicas para mapas de Campos de Batalha (Nota 2)
bg_magic_attack_damage_rate: 60

// Ajustes de dano de habilidades diversas para mapas de Campos de Batalha (Nota 2)
bg_misc_attack_damage_rate: 60

// Penalidade de esquiva (FLEE) em mapas de Campos de Batalha.
// NOTA: É em %, não absoluto, então 20 é -20% da sua esquiva total
bg_flee_penalty: 20

// Intervalo antes de atualizar os mini-pontos do mapa dos membros do Campo de Batalha (milissegundos)
bg_update_interval: 1000

// Antes de um jogador ser teleportado para um Campo de Batalha a partir da Fila de Campos de Batalha,
// verificar se o mapa atual do jogador possui MF_NOWARP.
bgqueue_nowarp_mapflag: no
