//--------------------------------------------------------------
// Arquivo de Configuração de Batalha do rAthena
// Originalmente traduzido por Peter Kieser <pfak@telus.net>
// Tornado em inglês mais simples por Ancyker
//--------------------------------------------------------------
// Nota 1: O valor é um seletor de configuração (on/off, yes/no ou 1/0)
// Nota 2: O valor é em porcentagem (100 significa 100%)
//--------------------------------------------------------------

// Ao criar uma guilda, um Emperium é consumido? (Nota 1)
guild_emperium_check: yes

// Limite máximo de imposto em um membro da guilda.
guild_exp_limit: 50

// Número máximo de castelos que uma guilda pode possuir (0 = ilimitado)
guild_max_castles: 0

// Ativar atraso das habilidades de guilda ao relogar?
// 0 - Salva o tempo de recarga (cooldown) e continua ao relogar.
// 1 - Não salva o tempo de recarga e reinicia o temporizador ao relogar.
// Padrão nos servidores oficiais: 1 para Pré-Renovação, 0 para Renovação
//guild_skill_relog_type: 0

// Atraso em milissegundos que é aplicado às habilidades de guilda.
// A configuração oficial é 5 minutos (300000 ms).
// Nota: Isso foi alterado na renovação em favor do tempo de recarga individual das habilidades.
guild_skill_relog_delay: 300000

// Ajuste de dano corpo a corpo (sem habilidades) para batalhas WoE (Guilda vs Guilda) (Nota 2)
gvg_short_attack_damage_rate: 80

// Ajuste de dano à distância (sem habilidades) para batalhas WoE (Guilda vs Guilda) (Nota 2)
gvg_long_attack_damage_rate: 80

// Ajuste de dano de habilidades de armas para batalhas WoE (Guilda vs Guilda) (Nota 2)
gvg_weapon_attack_damage_rate: 60

// Ajuste de dano de habilidades mágicas para batalhas WoE (Guilda vs Guilda) (Nota 2)
gvg_magic_attack_damage_rate: 60

// Ajuste de dano de habilidades diversas para batalhas WoE (Guilda vs Guilda) (Nota 2)
gvg_misc_attack_damage_rate: 60

// Penalidade de esquiva (flee) em mapas GvG. O valor oficial é 20 (Nota 2)
// NOTA: É em %, não valor absoluto, então 20 é -20% da sua esquiva total
gvg_flee_penalty: 20

// A habilidade 'Glory of Guild' pode ser aprendida na janela da Guilda,
// e a mudança de emblema exige ela? (Nota 1)
// P.S: Esta habilidade não é implementada nos servidores oficiais
require_glory_guild: no

// Limite de alianças de guilda. O valor é de 0 a 3.
// Se você quiser mudar este valor, limpe a tabela de alianças da guilda.
// O padrão é 3
max_guild_alliance: 3

// Quando reexibir o aviso da guilda
// Ao teleportar (independente de mudar de mapa): 2 (oficial)
// Ao mudar de mapa: 1
// Não reexibir: 0 (desativado)
guild_notice_changemap: 2

// O maprespawnguildid deve matar clones também?
// Padrão: não
guild_maprespawn_clones: no

// Quanto tempo (em minutos) uma guilda deve esperar entre trocas de líder?
// Padrão: 1440 (1 dia)
// Use 0 minutos para desativar o atraso.
guild_leaderchange_delay: 1440

// É permitido trocar o líder da guilda durante a WoE?
// Padrão: não
guild_leaderchange_woe: no

// Somente o líder da guilda pode aceitar alianças?
// Padrão: não
guild_alliance_onlygm: no
