//--------------------------------------------------------------
// Arquivo de Configuração de Batalha do rAthena
// Originalmente traduzido por Peter Kieser <pfak@telus.net>
// Adaptado para um inglês mais simples por Ancyker
//--------------------------------------------------------------
// Nota 1: O valor é um seletor de configuração (on/off, yes/no ou 1/0)
// Nota 2: O valor é em porcentagem (100 significa 100%)
// Nota 3: O valor é um campo de bits. Se não houver descrição,
//         considere os tipos de unidades (1: Pc, 2: Mob, 4: Pet, 8: Homun)
//--------------------------------------------------------------

// Bloquear saída de parties, guildas ou clãs se eles tiverem uma instância ativa?
// Padrão: yes (Oficial)
instance_block_leave: yes

// Bloquear mudança de líder em parties ou guildas se eles tiverem uma instância ativa?
// Padrão: yes (Oficial)
instance_block_leaderchange: yes

// Bloquear convites para parties ou guildas se eles tiverem uma instância ativa?
// Isso também bloqueia entrar em parties, guildas ou clãs que tenham uma instância em andamento.
// Padrão: yes (Oficial)
instance_block_invite: yes

// Bloquear expulsão em parties ou guildas se eles tiverem uma instância ativa?
// Padrão: yes (Oficial)
instance_block_expulsion: yes
