//--------------------------------------------------------------
// Arquivo de Configuração de Batalha do rAthena
// Originalmente traduzido por Peter Kieser <pfak@telus.net>
// Adaptado para um inglês mais simples por Ancyker
//--------------------------------------------------------------
// Nota 1: O valor é um interruptor de configuração (on/off, yes/no ou 1/0)
// Nota 2: O valor está em porcentagem (100 significa 100%)
// Nota 3: O valor é um campo de bits. Se nenhuma descrição for dada,
//         assuma tipos de unidade (1: Pc, 2: Mob, 4: Pet, 8: Homun, 16: Mercenário, 128: NPC, 512: Elemental)
//--------------------------------------------------------------

// O cast de habilidades deve ser cancelado quando afetado por curse/stun/sleep/etc (inclui silence)? (Nota 3)
status_cast_cancel: 0

// Certas alterações de status de habilidades devem ser removidas ao deslogar?
// 0 = (Padrão) Remove apenas status que possuem a flag SCF_NO_SAVE.
// 1 = Remove buffs negativos (status marcados como debuff)
// 2 = Remove buffs positivos.
// 3 = Remove todos.
debuff_on_logout: 0

// Ajuste para a taxa natural de resistência contra alterações de status.
// Se 50, a defesa contra status é reduzida pela metade, e você precisa do dobro
// de atributos para bloqueá-los
// (ex: 200 vit para bloquear completamente stun)
pc_status_def_rate: 100
mob_status_def_rate: 100

// Resistência máxima a alterações de status. (100 = 100%)
// NOTA: Cartas e equipamentos podem ultrapassar esse limite, então ele se aplica apenas à resistência natural.
pc_max_status_def: 100
mob_max_status_def: 100
