name: Compilar servidores com diferentes versões de pacote
# build_servers_packetversions.yml

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      # Sempre executar todas as Github Actions se um workflow ou algo relacionado ao CI for alterado
      - '.github/workflows/**'
      - 'tools/ci/**'
      # Este workflow deve rodar quando um arquivo em um diretório de código-fonte for modificado
      - 'src/**'
      - '3rdparty/**'

jobs:
  build:
    # O Github Actions verifica por '[ci skip]', '[skip ci]', '[no ci]', '[skip actions]' ou '[actions skip]'
    # (mas não versões com hífen). Isso é um pega-tudo caso alguém abra um Pull Request no automático.
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          # O label ubuntu-latest atualmente aponta para ubuntu-24.04.
          # Disponíveis: ubuntu-24.04, ubuntu-22.04
          os: [ubuntu-latest]
          # Versões antigas do GCC não estão disponíveis via repositórios padrão do apt
          gcc: ['11']
          # Executamos verificações de build tanto para Renewal quanto para PRE-Renewal
          mode: ['PRE','RE']
          # Verificar sucesso do build para diferentes versões de packet
          packetver: ['20211103', '20200902', '20200401', '20180620', '20151104']

    steps:
      - uses: actions/checkout@v4

      # Um simples 'yes' ou 'no' pode ser confuso, então usamos nomes legíveis
      # e depois convertemos para uso no compilador
      - name: Processar variáveis - PRE
        if: ${{ matrix.mode == 'PRE' }} 
        run: |
          echo "PRERE=yes" >> $GITHUB_ENV
      - name: Processar variáveis - RE
        if: ${{ matrix.mode == 'RE' }} 
        run: |
          echo "PRERE=no" >> $GITHUB_ENV

      - name: Atualizar e instalar pacotes
        # Os runners Ubuntu já possuem a maioria dos pacotes necessários para compilar o rAthena
        # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
        run: |
          sudo apt update
          sudo apt install zlib1g-dev libpcre3-dev gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}

      - name: Iniciar MySQL
        run: sudo systemctl start mysql.service

      - name: Configurar banco de dados e importar dados das tabelas
        run: ./tools/ci/sql.sh

      - name: Comando - configure
        env:
            CONFIGURE_FLAGS: 'CC=gcc-${{ matrix.gcc }} CXX=g++-${{ matrix.gcc }} --enable-prere=${{ env.PRERE }} --enable-packetver=${{ matrix.packetver }} --enable-buildbot=yes'
        run: ./configure $CONFIGURE_FLAGS

      - name: Comando - make clean
        run: make clean

      - name: Comando - make all
        run: make all
